export const tips = {
    paramsTip:'Put your desired score and defined percentage for scorecard.  If you don’t have ones then keep the current setting',
    timeSelectionTip:'select the time frame you want to see general overall score',
    redYellowColorTip:'Red is below average score, Yellow is between average and target score, Green is above target score, ALL includes all score ',
    parameterTip:'Put your desired score and defined percentage for scorecard.  If you don’t have ones then keep the current setting',
    onTimeDeliveryTip:'Select Accept Early Delivery if early delivery is not relevant for your on time delivery score ',
    recievingBufferDayTip:'this is your warehouse receiving time ',
    orderAcknowledgeDay:'this is the general days take for your vendor to acknowledge your order.',
    priceDayVarianceMessage:'This is day range you use to compare your purchase price variance. ex. You want to compare the price with the one between 90 days and 365 days in the past.',
    lineChartReportMessage:'This is day interval how you want to see your chart in report',
    byVendorMessage:'This is how you want to link your commodity to Material or Vendor',
    metricsWeightMessage:'this is where you can weigh your focus.  If you think on time delivery is more important then you can weigh it more.  Total is 100',
    ncrRawDataSetting:'this is NCR Report you uploaded',
    poHistoryRawDataSetting:'this is PoHistory Report you uploaded',
    poOpenOrderReportSetting:'this is Open Order Report you uploaded',
    buyerRawDataSetting:'this is Buyer Report you uploaded',
    vendorRawDataSetting:'this is vendor/commodity information you uploaded.',
    plantRawDataSetting:'this is plant information you uploaded.',
    plantTargetDataSetting:'this is plant target you uploaded.',
    buyerTargetDataSetting:'this is buyer target you uploaded.',
    commodityTargetDataSetting:'this is commodity target you uploaded.',
    vendorTargetDataSetting:'this is vendor target  you uploaded.',
    materialTargetDataSetting:'this is material target you uploaded.',
    emailMessage:'this is option for email send . want to view first or send',
    poRawHeading:'click on it to see pohistory raw data',
    ncrHeading:'click on it to see non conformance report data',
    buyerHeading:'click on it to see buyer report data',
    vendorHeading:'click on it to see vendor report data',
    plantHeading:'click on it to see plant report data',
    uploadFile:'select a file type then import it by clicking on upload button',
    importFile:`select a file type to import it's template by clicking on download button`,
    downloadButton:`click to download the selected file type template`,
    proceedButton:`click to save the data`,
    otdStatistics:`Stats for otd`,
    ncrStatistics:`Stats for ncr`,
    ppvStatistics:`Stats for ppv`,
    ltaStatistics:`Stats for lta`,
    colorStatistics:`Stats for color zone`,
    vendorSelection:`select vendor for comparison`,
    commoditySelection:`select commodity for comparison`,
    plantSelection:`select plant for comparison`,
    execution:`click to execute on the selected data`,
    endDate:`select end date for data comprison`,
    startDate:`select start date for data comprison`,
    compareVendorButton:`click to compare data in between selected vendor`,
    otdDetail:`click to see otd detail`,
    ncrDetail:`click to see ncr detail`,
    ppvDetail:`click to see ppv detail`,
    ltaDetail:`click to see lta detail`,
    sendReport:`click to send report`,
    selectReport:`select report to send`,
    sendDirect:`select to send report without viewing`,
    viewFirst:`select to send report after viewing`,
    colorZone:'show color zone stats',
    vendorTotalScore:'show vendor total score'
}


